#!/usr/bin/env node
/**
 * Regenerates public/data/products.json and public/feed.csv from
 * api/_lib/catalog.js and shop.config.js.
 *
 * Run this any time you edit prices, add/remove products, or change
 * SITE_URL in shop.config.js:
 *
 *   node scripts/build.js
 *
 * Then commit + redeploy.
 */
const fs = require("fs");
const path = require("path");

const catalog = require("../api/_lib/catalog.js");
const config = require("../shop.config.js");

const outDir = path.join(__dirname, "..", "public", "data");
fs.mkdirSync(outDir, { recursive: true });

// ---- public/data/products.json (safe display data for the frontend) ----
const publicProducts = catalog.map((p) => ({
  id: p.id,
  title: p.title,
  description: p.description,
  price: p.price, // null means "not yet priced" -> frontend disables Buy Now
  currency: p.currency || "USD",
  image: p.image,
  brand: p.brand,
  category: p.category,
  availability: p.availability,
  buyable: !p.needsReview && p.price != null && !!p.image,
}));

fs.writeFileSync(
  path.join(outDir, "products.json"),
  JSON.stringify(publicProducts, null, 2)
);

// ---- public/feed.csv (Meta/Instagram Commerce product feed) ----
// Spec: https://www.facebook.com/business/help/120325381656392
const headers = [
  "id",
  "title",
  "description",
  "availability",
  "condition",
  "price",
  "link",
  "image_link",
  "brand",
  "google_product_category",
];

function csvEscape(value) {
  if (value == null) return "";
  const s = String(value);
  if (/[",\n]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

const rows = [headers.join(",")];
let skipped = [];

for (const p of catalog) {
  if (p.needsReview || p.price == null || !p.image) {
    skipped.push(`${p.id} — ${p.title}`);
    continue; // don't publish incomplete listings to the feed
  }
  const productUrl = `${config.SITE_URL}/product.html?id=${encodeURIComponent(
    p.id
  )}`;
  const row = [
    p.id,
    p.title,
    p.description,
    p.availability,
    p.condition,
    `${p.price.toFixed(2)} ${p.currency || "USD"}`,
    productUrl,
    p.image,
    p.brand,
    p.category,
  ]
    .map(csvEscape)
    .join(",");
  rows.push(row);
}

fs.writeFileSync(path.join(__dirname, "..", "public", "feed.csv"), rows.join("\n") + "\n");

// ---- public/shop-config.js (browser-safe copy of shop.config.js) ----
const shopConfigJs = `// AUTO-GENERATED by scripts/build.js from shop.config.js — do not edit directly.
window.SHOP_CONFIG = ${JSON.stringify(
  {
    SHOP_NAME: config.SHOP_NAME,
    TAGLINE: config.TAGLINE,
    INSTAGRAM_HANDLE: config.INSTAGRAM_HANDLE,
    CONTACT_EMAIL: config.CONTACT_EMAIL,
    AMWAY_STOREFRONT_URL: config.AMWAY_STOREFRONT_URL,
    SITE_URL: config.SITE_URL,
  },
  null,
  2
)};
`;
fs.writeFileSync(path.join(__dirname, "..", "public", "shop-config.js"), shopConfigJs);

// ---- Static footers baked directly into the HTML ----
// These do NOT depend on client-side JS running correctly, so the Instagram
// handle / email / Amway link always render even if a script fails to load.
function esc(s) {
  return String(s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function footerHtml(variant) {
  const parts = [];
  if (variant === "full" && config.INSTAGRAM_HANDLE) {
    const handle = config.INSTAGRAM_HANDLE.replace(/^@/, "");
    parts.push(
      `  <p>Follow us on Instagram <a href="https://instagram.com/${encodeURIComponent(
        handle
      )}" target="_blank" rel="noopener">${esc(config.INSTAGRAM_HANDLE)}</a></p>`
    );
  }
  if (config.CONTACT_EMAIL) {
    parts.push(
      `  <p>Questions? Email <a href="mailto:${esc(config.CONTACT_EMAIL)}">${esc(
        config.CONTACT_EMAIL
      )}</a></p>`
    );
  }
  if (variant === "full" && config.AMWAY_STOREFRONT_URL) {
    parts.push(
      `  <p><a href="${esc(
        config.AMWAY_STOREFRONT_URL
      )}" target="_blank" rel="noopener">Official Amway IBO storefront</a></p>`
    );
  }
  return parts.join("\n");
}

const publicDir = path.join(__dirname, "..", "public");
const footerTargets = [
  { file: "index.html", variant: "full" },
  { file: "product.html", variant: "full" },
  { file: "cart.html", variant: "full" },
  { file: "checkout.html", variant: "minimal" },
  { file: "success.html", variant: "minimal" },
];

for (const { file, variant } of footerTargets) {
  const filePath = path.join(publicDir, file);
  if (!fs.existsSync(filePath)) continue;
  const html = fs.readFileSync(filePath, "utf8");
  const marker = /<!-- FOOTER:START.*?-->[\s\S]*?<!-- FOOTER:END -->/;
  if (!marker.test(html)) {
    console.warn(`  (no FOOTER markers found in public/${file} — skipped)`);
    continue;
  }
  const replacement = `<!-- FOOTER:START (auto-generated by scripts/build.js from shop.config.js — do not hand-edit between these markers) -->\n${footerHtml(
    variant
  )}\n<!-- FOOTER:END -->`;
  fs.writeFileSync(filePath, html.replace(marker, replacement));
}

console.log(`Built public/data/products.json (${publicProducts.length} products)`);
console.log(`Built public/feed.csv (${rows.length - 1} products published)`);
if (skipped.length) {
  console.log(`Skipped from feed (missing price/image or needsReview):`);
  skipped.forEach((s) => console.log(`  - ${s}`));
}
